[package]
name = "ariel-os-boards"

[package.edition]
workspace = true

[package.license]
workspace = true

[package.rust-version]
workspace = true

[dependencies.ariel-os-embassy-common]
workspace = true

[dependencies.cfg-if]
workspace = true

[dependencies.ariel-os-hal]
workspace = true

[features]
no-boards = []
