name: PR title checks

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pr-title:
    name: Lint PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - name: Install committed
        uses: taiki-e/install-action@14083e64ac8cf1f5e54356df00b9779b23e192a1 # v2
        with:
          tool: committed

      - run: committed --config committed.toml --commit-file <(echo "${PR_TITLE}")
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
